### ISSUE TITLE
Custom cursor CSS not preserved in window

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#2250]
Demo: https://dl.dropboxusercontent.com/u/15217362/nwcursor.zip

Setting a custom CSS cursor using the "cursor" style (in this case set to a data URI) does not preserve the cursor on Windows 8.1.

Steps to reproduce:
1. Launch the demo. Notice the yellow cursor.
2. Move the mouse outside the window, and back in again.
3. Try moving the mouse outside and in again at different speeds.

Observed result:

The mouse cursor inside the node-webkit window seems to be randomly chosen between normal Windows cursor, a window border resize cursor, or the yellow custom cursor.

Expected result:

The yellow custom cursor should always display when the mouse is inside the node-webkit window.
##

**Comment by morgondag** [comment]
Can confirm the steps above. 
Having a nw.js window open then opening another application, and then refocus the nw.js window the cursor defaults to window-resize cursor. All types of CSS cursors are overwritten by the resize-cursor.

**Comment by egaliano** [comment]
it's a huge block to use nw.js in kiosk apps =/ are you planning to solve this soon ?

**Comment by Fib100** [comment]
This issue is still occurring for me using nwjs v0.30. If my mouse cursor leaves the nwjs window, the custom cursor gets replaced with a standard windows cursor.

**Comment by Fib100** [comment]
@rogerwang @AshleyScirra Can we please re-open this issue. It may have been fixed in the past, but it seems to me that it has resurfaced.

**Comment by Fib100** [comment]
@rogerwang @AshleyScirra @morgondag has anyone confirmed that this bug has re-surfaced? Please see my "minimal example app" from my above comment. It was built using nwjs v0.30.

I have a game published on Steam and when in windowed mode, the cursor gets all messed up. It makes it look amateurish.

**Comment by rogerwang** [comment]
@Christywl please try to reproduce. thanks.

**Comment by Christywl** [comment]
I can reproduce this issue with @Fib100's  sample:
The mouse cursor is randomly changed between a normal Windows cursor, a window border resize cursor, or the custom cursor.

**Comment by AshleyScirra** [comment]
We still get reports of this, e.g.: https://www.construct.net/forum/construct-2/closed-bugs-22/cursor-image-disappears-135883

This report is nearly 4 years old now. Is it possible this could be fixed?

**Comment by rogerwang** [comment]
could it be reproduced with a Chrome App in Chrome browser?

**Comment by TheRealDannyyy** [comment]
@rogerwang Could also reproduce this using NWjs v0.29.0 by simply moving the cursor outside the window and back inside. (The person who reported it could also reproduce it using NWjs v0.31.0.)

Here is the requested Chromeapp: [Cursor Bug (Chromeapp)](https://github.com/nwjs/nw.js/files/2189025/Cursor.Bug.Chromeapp.zip)
I could not reproduce this issue using the Chromeapp and Chrome M67.

**Comment by TheRealDannyyy** [comment]
Can't reproduce this issue using NW.js v0.32.0, using this [example project](https://github.com/nwjs/nw.js/files/2228314/package.zip) anymore. 
(OS: Windows 7 SP1; Unzip example project before use.)

**Comment by Fib100** [comment]
I just re-built my game using NW.js v0.32.0 and I confirm the issue is fixed as far as I can tell.

Thanks!

**Comment by trapless** [comment]
This works for me using NW.js v0.29.0
```javascript
window.onMouseLeave = () => {
  document.body.style.cursor = 'none';
};
window.onMouseEnter = () => {
  document.body.style.cursor = 'url("exmpl/dir/mycursor.png"), default';
};

document.addEventListener('mouseleave', onMouseLeave);
document.addEventListener('mouseenter', onMouseEnter);
```
