### ISSUE TITLE
nw.js 0.13.0alpha: inject-js-start, inject-js-end not working [$65]

### ISSUE THREAD

**Issue by scotttesler** [nwjs/nw.js#3538]
Neither of these seem to have any effect in nw.js 0.13.0alpha.

**Comment by rogerwang** [comment]
This is fixed in git and will be release with alpah2

**Comment by scotttesler** [comment]
@rogerwang Any idea when alpha2 will be released?

**Comment by rogerwang** [comment]
It would be in a week.

**Comment by rogerwang** [comment]
it's released just now: https://groups.google.com/d/msg/nwjs-general/zeC6SedUSFY/BlumrYJeVHYJ

**Comment by scotttesler** [comment]
@rogerwang This still doesn't seem to be working. Is there an example application I can take a look at for alpha2 with `inject-js-start`?

**Comment by rogerwang** [comment]
@scotttesler pls check https://github.com/nwjs/nw.js/blob/nw13/test/remoting/new-win-policy/index.html#L8

The test case checks inject-js-start and new-win-policy together. It doesn't check inject-js-start in manifest but it should work.

btw, require() is now nw.require() in nw13.

**Comment by scotttesler** [comment]
I didn't know about the `nw.require()` change :+1: That works when I'm hitting something like an index.html that's a part of the project. However, `nw.require()` doesn't work when, in `package.json`, the `main` is a remote URL. This does work in nwjs0.12.x. Should I open another issue / are there plans to port that feature?

**Comment by scotttesler** [comment]
Perhaps the issue is that `node-remote` hasn't yet been ported to nw13. If my `main` in package.json is a URL, I get `Uncaught ReferenceError: nw is not defined` in the application from the injected JS file.

**Comment by lili21** [comment]
Have you fixed that ? @scotttesler . my main in `package.json` is also a URL, and get the same error.

**Comment by scotttesler** [comment]
@lili21 I never got it working
