### ISSUE TITLE
nwjs 0.13.0-alpha1 - boot error [$5]

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#3571]
Hello,
I'm trying to run the same app which works on 0.12 version.

When I try to lunch it I see an error (alert):

Impossible to load the extension: /private/var/folders/l2/6vtky5ps3_qg5w_jdsm9mwf80000gn/T/.com.myapp.kYvjFR. Invalid value for 'app.urls[0]': Missing scheme separator.

Console log
[0611/090930:INFO:nw_package.cc(174)] ./dist/osx/x64/MyApp.app/Contents/MacOS/MyApp
[3616:1799:0611/090932:ERROR:url_pattern_set.cc(240)] Invalid url pattern: chrome://print/*

OS: MacOS 10.8.5

**Comment by sirisian** [comment]
Same on Windows 7 here.

**Comment by b1rdex** [comment]
Confirmed in v0.13.0-alpha3 on windows 10.

The problem is with `node-remote` package field.
In [wiki description](https://github.com/nwjs/nw.js/wiki/Manifest-format#node-remote) `scheme` was optional, but looks like it's required now.

So fix is to provide `http://` or whatever you have scheme in `node-remote` field.

@rogerwang I think this is bug and should be reverted to previous behaviour.

**Comment by b1rdex** [comment]
This bug is confirmed by developers: https://github.com/nwjs/nw.js/blame/0ca348429070d39fc098854566dd8502edc3365a/src/nw_content.cc#L461-L464

**Comment by mitchross** [comment]
I can confirm @b1rdex 's fix as working.

**Comment by cbenjemia** [comment]
is there a solution until the fix ?

**Comment by HusainJaffer** [comment]
@cbenjemia  
To quote @b1rdex put node-remote to   "node-remote": "http://<Something>"
Mine is  "node-remote": "http://localhost"
In your package.json

**Comment by tiitremmel** [comment]
Any info when it will be fixed?

**Comment by hammadasad** [comment]
@HusainJaffer 
Your suggestion:
"node-remote": "http://localhost"
Works perfectly fine. Thanks!

**Comment by ghostoy** [comment]
The `node-remote` spec is changed since 0.13.0. See [migration notes from 0.12 to 0.13](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#manifest-format).

**Comment by Gimmeaphatbeat** [comment]
How to specify a "file" path for `node-remote` ?

This doesn't work: `"node-remote": "file:///*"`

**Comment by Gimmeaphatbeat** [comment]
This also doesn't work:

package.json:
`"node-remote": ["https://*/*"],`

```
var win = nw.Window.get();

nw.Window.open('https://www.google.co.uk', {}, function(new_win) {
  // do something with the newly created window
});
```

Then on the new window, open Dev tools and on Console type `nw`:

`Uncaught ReferenceError: nw is not defined(…)`

**Comment by loretoparisi** [comment]
I do not understand why protocol scheme `http://` or whatever should be mandatory supposed that I'm using local files only like

```javascript
node-remote : 'index.html'
```

So, in `v0.13.0-beta4` - http://nwjs.io/blog/v0.13.0-beta4/ this is not working (scheme separator needed).

**Comment by ghostoy** [comment]
This issue should be solved.

@AndryBray The spec of `node-remote` is changed to using [match patterns](https://developer.chrome.com/extensions/match_patterns). See the good and examples for details.

@Gimmeaphatbeat `node-remote` for `"https://*/*"` is working. And `"file://*/*` does NOT. But mostly local files inside your app can be specified using relative path. You don't have to use `file://` scheme.

**Comment by loretoparisi** [comment]
@ghostoy so we can use `"node-remote" : "*://index.html"`?

**Comment by ghostoy** [comment]
@loretoparisi It's not a valid pattern. If you want to match all `index.html` under any scheme and any host, use `*://*/index.html`.

**Comment by rogerwang** [comment]
close per https://github.com/nwjs/nw.js/issues/3571#issuecomment-209302569

**Comment by lili21** [comment]
@ghostoy still don't get how to make local files work .
"node-remote": "relative/path/to/file"  does not work.

**Comment by ghostoy** [comment]
@lili21 `node-remote` is a pattern of a full URL. `relative/path/to/file` is not valid because it missed scheme and host name parts. See [this document](https://developer.chrome.com/extensions/match_patterns) for the format of the pattern.

**Comment by lili21** [comment]
@ghostoy  file scheme ? still not work. 
"node-remote": "file:///src*"

**Comment by ghostoy** [comment]
@lili21 I see. Currently `file:` scheme with node is not supported.

Usually if HTML files are within the directory of your app, you don't have to use `file:` scheme and `relative/path/to/file.html` should be working without `node-remote`.

But if you are referencing files in absolute path, like `/root/path/file.html`, or paths in parents directories of your app, like `../path/to/file.html`, it's not supported.

Some workarounds for you if your app is the second case:

1. Refactor your app to contain all files within a same directory if possible. Or
2. Host a local webserver and set `node-remote` in `package.json`. And refactor requests to `file:` by using `http:`.

Please also post your requirements [here](https://github.com/nwjs/nw.js/issues/new) and we'll seek to support it.
