### ISSUE TITLE
Native Module Makes NW.js Crash

### ISSUE THREAD

**Issue by cotejp** [nwjs/nw.js#4338]
Whenever I try to use the `serialport` module in NW.js v0.13.0-beta4 on Mac OS X.10 (Yosemite), the application crashes with the following error:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v87Isolate10GetCurrentEv
  Referenced from: /Users/jpcote/Desktop/PiezoMusic/node_modules/serialport/build/Release/node-webkit-v0.13.0-beta4-darwin-x64/serialport.node
  Expected in: dynamic lookup
```

The `serialport` module uses a native binary. I successfully compiled it using `node-pre-gyp` as suggested [here](https://github.com/nwjs/nw.js/wiki/build-native-modules-with-nw-gyp):

```
node-pre-gyp rebuild --runtime=node-webkit --target=0.13.0-beta4
```

Here's a simple test page to reproduce the problem:

```
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <title>NW.js 0.13 Johnny-Five Test</title>
    <script>
      require('nw.gui').Window.get().showDevTools();
      var five = nw.require("johnny-five");
      var board = new five.Board();
    </script>
  </head>

  <body>
    NW.js 0.13 Johnny-Five Test
  </body>

</html>
```

The problem seems to be Mac specific. I was able to use the `serialport` module in Windows 7 without any problems.

**Comment by nightwend** [comment]
I met the same issue for Mac OS X. I tried with some very simple examples, got the same error.
I think it may related to libnode.dylib introduced in 0.13. I can find the missed symbol in libnode.dylib in version 0.13. But the symbol is in nwjs binary for 0.12.

**Comment by geisbruch** [comment]
I have the same issue with beta5, some one have found a solution ?

**Comment by cotejp** [comment]
I was able to make NW.js 0.13 work with browser-serialport. The browser-serialport module is a replacement for node-serialport that uses `chrome.serial` when available. You might want to look into it.

**Comment by nightwend** [comment]
Unfortunately, I need to build my own module so your workaround  does not work for me.
I built a simple demo for reproduce the issue. But I have no idea how to fix it.
https://github.com/nightwend/nwjs-demos

**Comment by kimtn-bitmark** [comment]
Got the same error when i'm trying to use native module

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v87Isolate10GetCurrentEv
  Referenced from: /Users/thinhuockim/Documents/project/bitmark/nodewebkit-sample/tweetnacl-sample-mac/node_modules/libtorrent-nodewrap/node_modules/ref/build/Release/binding.node
  Expected in: dynamic lookup
```

**Comment by cuongle121** [comment]
I got exact the same error with my own module on my Mac - OSX 10.11.2.
The problem only happens for me on OSX, when I build it in the VM (Ubuntu 14.04), it runs just fine.

**Comment by binle** [comment]
I switched to 0.13 beta5 recently and got this error on Mac too. I need my C++ modules to run on nwjs to demo the app to some customers. I really hope this issue could be fixed soon. How is the status?
Thanks.

**Comment by rogerwang** [comment]
Thanks for the sample. Will fix it soon.

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
btw, native modules built by node-gyp/npm is now supported : https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ

**Comment by cotejp** [comment]
Excellent. Thanks You!

**Comment by busykai** [comment]
I'm still seeing the issue with module `ref@1.3.2` (`nwjs` at 401736db). Same thing whether the module is built with `node-gyp` or `nw-gyp`. I'm not sure which commit between beta6 and beta7 tags fixes this...

**Comment by rogerwang** [comment]
@busykai it was fixed in the Chromium repo.

**Comment by busykai** [comment]
Thank you! I thought I was missing something.
