### ISSUE TITLE
Transparency + Click-through clicks through floated elements

### ISSUE THREAD

**Issue by needo2** [nwjs/nw.js#4846]
##### I got it working by setting initial width and height to big numbers. It didn't work because resizing done via `win.resizeTo(screen.availWidth, screen.availHeight);` wasn't affecting the clickable area apparently 

- nw.js v0.14.3 x64
- Windows 10 x64 Home, Build 10586

I can click on divs when they don't float but clicks go through them when they float

Style: `div.right {width: 200px; float: right;}`
Same issue with `.parent {position:relative;}.child{position:absolute;right:0;}` instead of float:right

Clicking at where-they-would-be-without-float doesn't work either (if it's any relevant)

![image](https://cloud.githubusercontent.com/assets/9450683/15249540/bf4e8a66-1928-11e6-9a68-217e6cd2e92c.png)

-- Extra info --

Ran with `nw . --disable-gpu --force-cpu-draw`

window
```
"frame": false,
"toolbar": false,
"transparent": true,
"resizable": false
```

body style
```
body {
	background-color:rgba(0,0,0,0);
}
```

Please tell me if I missed anything I'll update

**Comment by rogerwang** [comment]
@jtg-gg could you please check this?

**Comment by jtg-gg** [comment]
@needo2 can you send me the sample app as zip file ?

**Comment by needo2** [comment]
I put it on tinyupload because when I try to upload here, it rejects saying file type isn't supported even that it's a zip
http://s000.tinyupload.com/index.php?file_id=03419548818930588927

**Comment by jtg-gg** [comment]
@needo2 I am still debugging, but I found a work around, if you specify the initial window (in package.json) big enough, then resize it down, it will works, but I know it is ugly

**Comment by jtg-gg** [comment]
@needo2 I've it fixed, waiting for @rogerwang to accept my pull request https://github.com/nwjs/chromium.src/pull/18

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by wesamco** [comment]
@jtg-gg @rogerwang i'm having a similar issue, and I think it's the same cause.
https://github.com/jtg-gg/chromium.src/blob/cdeae7658e12fea2d3a2ff9b1dd719a0064d3b6f/ui/views/win/hwnd_message_handler.cc#L1157
i'm running nwjs-sdk-v0.15.0-rc2-win-x64(meaning I didn't have the fixed next nightly build bits @rogerwang ), Windows 10 14323. and I have a dual monitor setup, my laptop on the left and 1080p monitor on the right.
I have a transparent, frameless, non realizable fullscreen window, click thrugh enabled (gpu disabled, force cpu)
after interacting with the elements on the page a few times (clicking, dragging etc), the issue occurs, which is that the window visible (does not get minimize or resized or anything, stays as it is visible) but can't click the elements anymore, and I can right click on the element and the desktop context menu opens, meaning it is clicking thought the element.

@jtg-gg i tried your quick ugly fix, and did set both width's and height's initial values of the window to 10000 and after load set them to (calculated all screens size) (the dual monitors in my case), after that it fixed the dragging on the laptop's screen (left) all the way to the right to some of the second screen, but after I pass that area with dragging the rectangle the window becomes "all click throughable". 

long comment, but I hope my description of the issue can help you diagnose the cause and fix it.

**Comment by jtg-gg** [comment]
@wesamco I've fixed the issue, can you try the latest nightly build ?
do you still have problem ? if yes, can send me a small app so I can debug it

**Comment by wesamco** [comment]
@jtg-gg  I installed the latest nightly build, and tried it, the issue wasn't fixed.
here is a video capture https://www.youtube.com/watch?v=0Y8MwzwIFUc

- I think i found what is the issue, 
https://github.com/jtg-gg/chromium.src/blob/cdeae7658e12fea2d3a2ff9b1dd719a0064d3b6f/ui/views/win/hwnd_message_handler.cc#L1157 
in this method, the new updated rectangle bounds of the window gets updated to wrong bounds (which seems to be the bounds of the primary screen (see Screen shot)), but the position of the window doesn't change. 
- the bug is not in my code, I checked the window covers all the screens (I can drag the rectangle to the far left of the second monitor) 

- see the screenshot and explanation, <img src="http://i.imgur.com/bC085Bs.jpg">
the horizontal red line operates the two monitors, and the blue line marks the far right end of the newly rendered window bounds. the new bounds of the window are the same bounds of the primary screen of the system.
