### ISSUE TITLE
React devtools extension in webview stuck "Connecting to React..."

### ISSUE THREAD

**Issue by frankhale** [nwjs/nw.js#4878]
NW.js 0.15 RC2 SDK x64
Windows 10 x64
React devtools extension 0.14.9

**I'm using a webview to load my React app**

I'm trying to get the React devtools extension working but it's always stuck trying to connect. When you open the React tab in devtools it says the following:

> Connecting to React... If this is React Native, you need to interact with the app (just tap the screen) in order to establish the bridge.

I've followed the directions here:

http://docs.nwjs.io/en/v0.13.0-beta7/For%20Users/Debugging%20with%20DevTools/

> Devtools extensions are fully supported, including the one for ReactJS etc. To use it, add the permission “chrome-extension://*” to manifest.json of the devtools extension, and load it with ‘–load-extension=path/to/extension’ when nw is started. The files for devtools extensions can be copied from extension folder of Chrome browser after you install them from Chrome Web Store.

Am I doing something wrong?

**Comment by rogerwang** [comment]
We have a test case with sample React app and the React devtools extension to guard this feature. Could you please try it first to make sure your steps are correct?

https://groups.google.com/d/msg/nwjs-general/jcsYqmqhQfE/v0lH0badEQAJ
https://github.com/nwjs/nw.js/tree/nw14/test/sanity/react-devtools-extension

**Comment by rogerwang** [comment]
merge this issue with #612

**Comment by frankhale** [comment]
Not sure what you want me to try. I am doing what the docs website says but I get the results stated above.

**Comment by rogerwang** [comment]
You can try it first with our copy of React devtools extension and the sample app.

**Comment by frankhale** [comment]
Yes your test case works. I should have mentioned I am using a webview to load my React app.

**Comment by frankhale** [comment]
I've edited my initial issue to denote that I am doing this from a webview. React devtools loads fine but will never connect to my code. Can this issue be reopened as it pertains to devtools extensions inside a webview?

**Comment by rogerwang** [comment]
Is it supported with webview in the Chromium browser?

**Comment by frankhale** [comment]
I don't know

**Comment by rogerwang** [comment]
I don't think it's supported. So please submit the issue to React Devtools Extension project.

**Comment by frankhale** [comment]
To be fair, opening my app directly inside NW.js the React devtools still don't work. I get a message saying "Waiting for roots to settle.. blah blah". Opening my app in Chrome it works fine and React devtools extensions is okay and usable.

**Comment by rogerwang** [comment]
Then could you please upload your app so I can reproduce it?

**Comment by frankhale** [comment]
If I am able to create a small reproducible test case I'll link it here.

**Comment by JasonFang93** [comment]
hello @frankhale how to resolve this requirements at last, and i have met this problem now?

**Comment by frankhale** [comment]
@JasonFang93 I've never got it to work. React devtools loads but it never connects to my app.

**Comment by frankhale** [comment]
On the other hand react-devtools works fine when I load my app in Electron

**Comment by JasonFang93** [comment]
i don't know how to load devtools extension for webview tag, could you write some example codes ?
btw, because devtool of webview in Electron can't  be docked in right instead of a new window, i use nwjs at last.

**Comment by frankhale** [comment]
You don't need to do anything special to make the react devtools load on a webview. You just start up nw.js using --load-extension /path/to/react/devtools

Additionally you need to add “chrome-extension://*” to the permissions array in the react devtools manifest.js. 

Even with that said, the devtools are being blocked from running which is why it always says "connecting to react..."

![react-devtools-blocked-from-running](https://user-images.githubusercontent.com/190154/28267526-6a3f5f08-6ac8-11e7-8853-17409a2268ca.PNG)

**Comment by JasonFang93** [comment]
Thanks a lot @frankhale

**Comment by frankhale** [comment]
Even using a webview partition doesn't seem to allow the react-devtools code to load

https://developer.chrome.com/apps/tags/webview#partition

**Comment by frankhale** [comment]
I just made a simple test case to demonstrate the problem, I'll upload it to github and post a link here:

![simple-test-case-nwjs-react-devtools-webview](https://user-images.githubusercontent.com/190154/28268550-affd2d82-6acc-11e7-965a-75b6940b8794.PNG)

**Comment by frankhale** [comment]
Here is a simple example to demonstrate the issue: https://github.com/frankhale/nwjs-react-devtools-webview-example

**Comment by Christywl** [comment]
I try above sample on Windows 8.1 with nwjs-sdk-v0.24.4. This issue is still reproduced. 
`nwjs-sdk-v0.24.4-win-x64\nw.exe --load-extension=react-devtools react-app`

**Comment by frankhale** [comment]
Just tried my simple test case (link above) in NW 0.25.2 and it's still the same problem. React Devtools still cannot connect to the app.

`VM71:5 GET chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js net::ERR_BLOCKED_BY_CLIENT`

**Comment by frankhale** [comment]
Just to add a bit more clarity to when @rogerwang said he didn't think this was supported. This scenario works fine in Electron so React devtools does indeed work inside a webview. Chromium supports this. I'm not sure how to work around this in NW.js though. Any help would be greatly appreciate it as I prefer NW.js over Electron due to it's fast paced releases and it's always current with Chrome and Node.

**Comment by frankhale** [comment]
Adding the following to the manifest of the React devtools extension makes the ERR_BLOCKED_BY_CLIENT go away but it still doesn't make the React devtools work unfortunately. It'll just say "Connecting to React..." forever.

`
 "webview": {
     "partitions": [
        {
          "name": "trusted",
          "accessible_resources": [ "<all_urls>" ]
        }
     ]
  }
`

**Comment by frankhale** [comment]
@Christywl any ideas? This issue is quite old now and there doesn't seem to be any way to get devtools to work when the app is loaded in a webview. Is there any work around I can try?

Additionally I tried the Vue Devtools and a Vue app loaded in a webview with similar results. Devtools load but app is never detected by the devtools extension. Just like React.

**Comment by frankhale** [comment]
Additionally it doesn't appear as though devtools work for pages loaded in iframes either. The react devtools aren't loading at all for a React app in an iframe.

**Comment by frankhale** [comment]
FYI, for those that may trip up on this issue and need a workaround, I just found one. It involves using the React-Devtools native app. https://github.com/facebook/react-devtools/tree/master/packages/react-devtools

This should work fine until devtools work in webviews/iframes in NW.js

**Comment by frankhale** [comment]
Maybe you can empower me to help work on this issue. Do you have any pointers on where to start looking in the code for this sort of thing?

**Comment by frankhale** [comment]
Any word if NW.js 0.26.0-beta1 resolves this issue?

**Comment by frankhale** [comment]
Unfortunately this issue still exists in NW.js 0.26.0-beta1. 

![disappointed-in-nwjs](https://user-images.githubusercontent.com/190154/30732135-14e04b34-9f3f-11e7-95c2-1843cebd74b0.PNG)

**Comment by rogerwang** [comment]
will see this soon. @Christywl could you please try with Chromium browser and see whether it reproduces with it?

**Comment by Christywl** [comment]
@rogerwang , how should I run this webview sample with the chrome? I just open the [nwjs-react-devtools-webview-example-master\react-app\index.html](https://github.com/frankhale/nwjs-react-devtools-webview-example/blob/master/react-app/index.html) with the chrome(React Devtools extension has added to chrome), it displays a blank page.
If I open http://react-toolbox.com with the chrome directly, react devtools extension works fine. 
@frankhale , I see you tried your app in the chrome before and react devtools extension works fine in the  https://github.com/nwjs/nw.js/issues/4878#issuecomment-220889624. Could you please share the way to check your sample and react devtools extension with the chrome?

**Comment by frankhale** [comment]
I actually don't know how to run this in Chrome to be honest. I do know that this scenario works fine in Electron. Additionally I tested the app running in NW.js using react-devtools app (link below, which provides an external way to debug react apps) and I was able to debug this app just fine.  

https://github.com/facebook/react-devtools/tree/master/packages/react-devtools

**Comment by frankhale** [comment]
I'll take some time to figure out how to make this into a chrome app for testing this scenario

**Comment by frankhale** [comment]
I created a Chrome App to test this but devtools extensions like Vue and/or React aren't loading for Chrome Apps so I am not sure how to test this.

**Comment by frankhale** [comment]
Normally I'd just let this go as there is a working solution using the React Devtools native app but Electron seems to be able to handle this scenario just fine so it can work I just don't know what is going on in NW.js that prevents React Devtools from connecting to apps inside a webview. I'll try to dig into Electron to see if they added any specific magic to allow Devtools extensions to work out of the box with pages loaded in webviews.

**Comment by frankhale** [comment]
Okay I may have a little bit more information here. So loading up the sample app (linked above) and debugging the React Devtools when it tries to connect to the React app I can see it's trying to use API's in `chrome.devtools` but they are not present in NW.js from within the webview. `chrome.devtools` is `null`. When React Devtools connects to your app it does so by using API's in there but it can't do that because `chrome.devtools` is `null`.

**Comment by frankhale** [comment]
The last comment in this summarizes what I found yesterday. I actually made a comment about it but deleted it because I was a little unsure but yeah it seems to be the case.

https://github.com/vuejs/vue-devtools/issues/249#issuecomment-332139702

> in nwjs webView chrome.devtools.inspectedWindow.tabId got null , so there will no message between the app context and chrome/src/devtools.js .
may be you have to modify the code , implement this code like shells/dev/src/devtools.js
enjoy~

**Comment by frankhale** [comment]
Okay so in a normal window React devtools (and I suspect others as well) work fine because `chrome.devtools` exists and has APIs needed by the devtools extensions. When using a webview and trying to use the devtools extensions `chrome.devtools` is undefined and breaks the devtools extensions. They cannot connect to the app because there are API's missing.

**Comment by rogerwang** [comment]
@frankhale thanks for your investigation. Will see why chrome.devtools is not defined there.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

support for chrome.devtools.inspectedWindow.tabId in webview was added.

**Comment by frankhale** [comment]
Thank you @rogerwang !!!

**Comment by frankhale** [comment]
Just tested the nightly build and it WORKS! THANKS YOU @rogerwang !!!!!!!!!!!

![react-devtools-from-within-webview](https://user-images.githubusercontent.com/190154/31032692-12b3cad8-a52b-11e7-86f7-5a5c70700c39.PNG)

**Comment by rogerwang** [comment]
Good to know it works.

**Comment by frankhale** [comment]
@rogerwang I'm trying to find the commit that has this change but I've been unable to find it. I'd like to see the code change that fixed this. Can you (somebody) link me to the actual commit?

**Comment by rogerwang** [comment]
@frankhale  it's fixed in the chromium repo. And the code we developed in that repo was under a master patch after 0.13. So it's not directly linked with specific bug fix. In 0.12 and previous versions we kept small commits there, but it was hard to rebase to new Chromium version in that way.

The fix is in the follow files if you're interested:
```
chrome/browser/extensions/api/tabs/tabs_api.cc
chrome/browser/extensions/extension_tab_util.cc
```

**Comment by frankhale** [comment]
Thank you. I'll take a look at it. =)

**Comment by frankhale** [comment]
I found it in the nwjs/chromium.src repo. I was actually looking in the nwjs repo which is why I couldn't find it. Thanks again for pointing me in the right direction!

**Comment by foolishchow** [comment]
Is in [10-13-2017](https://dl.nwjs.io/live-build/10-13-2017/nw25-ca9366c-223521f-a1df156-39bcff5/v0.25.5/) build ?  I found it is not fixed in osX in this.

**Comment by Christywl** [comment]
The issue still also occurs for me. @frankhale , which version do you use in https://github.com/nwjs/nw.js/issues/4878#issuecomment-333217674, I try the [latest nwjs nightly build](https://dl.nwjs.io/live-build/10-16-2017/nw26-744df00-edf758a-6de1a29-61e38b8/v0.26.0/) on Windows, this issue still happens. I download [your sample](https://github.com/frankhale/nwjs-react-devtools-webview-example) and the cmd is:
`C:\nwjs\bugs\4878\nwjs-react-devtools-webview-example-master>..\..\..\..\Users\WebQA\Downloads\nwjs-sdk-v0.26.0-win-x64\nw.exe react-app --load-extension=react-devtools`
Is there something missing in my test?

**Comment by rogerwang** [comment]
Could be a regression in nw26 branch. Reopen

**Comment by frankhale** [comment]
@Christywl, I tried the nightly 0.25.5 build from when Roger said it was working. I also tried a few days later but have not updated since. I was waiting for 0.25.5 to be officially released first.

**Comment by rogerwang** [comment]
@Christywl it's working for me with the nightly build you referred to. So close as no regression.

@frankhale there won't be any 0.25 release any more, as 0.26.0 will be released soon.

**Comment by frankhale** [comment]
Awesome thanks @rogerwang !!!

**Comment by frankhale** [comment]
Fix confirmed working in 0.26.0. Thanks so much @rogerwang !!!!

**Comment by AlexIII** [comment]
The issue seems to be back again. React devtools (3.6.0 and 4.0.6) work with nwjs 0.31.5, but not with 0.32.0 or any newer. (React tab in devtools is either empty or gets stuck on "Connecting to React...")

**Comment by rogerwang** [comment]
Will check it out. The test case with react devtools is passing...

**Comment by AlexIII** [comment]
Any news on that one? Still relevant.

**Comment by rogerwang** [comment]
@AlexIII I just tried the latest version. It works for me in the same way as in the test case: https://github.com/nwjs/nw.js/blob/nw43/test/sanity/react-devtools-extension/

**Comment by AlexIII** [comment]
@rogerwang I will try to reproduce the error and report here shortly.

**Comment by AlexIII** [comment]
@rogerwang I see that react devtools in the test are heavily outdated. Here's the latest version [react-devtools-4.2.1_0.zip](https://github.com/nwjs/nw.js/files/4002012/react-devtools-4.2.1_0.zip), which allows to replicate the bug. I believe any version 3.x.x or 4.x.x have this issue, as I previously have tried maybe ten different versions in futile attempt to find one that works.

**Comment by rogerwang** [comment]
@AlexIII I am using the latest version, as I said in the previous comment...

**Comment by AlexIII** [comment]
@rogerwang I thought you meant you used the latest NWjs version... Well I just tried clean win10 x64 + latest nw + latest react devtools and it still doesn't work. I just don't know what I'm doing wrong... Here's my whole test folder (Without nwjs, had to remove it from zip. It's too big.).
`nwjs-sdk-v0.43.2-win-x64` - from nwjs.io
`react-devtools-4.2.1_0` - from chrome browser extension folder
`react-devtools-extension` - test app from the link you gave
`run.cmd` - the command I run the app with:
```cmd
start nwjs-sdk-v0.43.2-win-x64\nw.exe --load-extension=react-devtools-4.2.1_0 react-devtools-extension
```

[react-devtools-test.zip](https://github.com/nwjs/nw.js/files/4002098/react-devtools-test.zip)

**Comment by rogerwang** [comment]
@AlexIII I haven't tried you app but here is what is working for me:
`nwjs.app/Contents/MacOS/nwjs --load-extension=4.2.1 --url=https://reactjs.org/docs/hello-world.html`

**Comment by AlexIII** [comment]
@rogerwang Interesting, the command you gave works for me too! Maybe because it's loaded via `--url`, I don't know. Btw, it was NOT _my_ app. It's the same app from [the link you gave](https://github.com/nwjs/nw.js/blob/nw43/test/sanity/react-devtools-extension/).
At this point I hope someone will try and confirm my finding, I really hope I'm not crazy 😄 😞

**Comment by rogerwang** [comment]
That app will not work because it's using a very old version of react,
which is not supported by the latest version of the extension.

**Comment by rogerwang** [comment]
btw, you'll need to change `manifest.json` in the extension so it will work on `chrome-extensions` protocol, which NW.js app uses.

**Comment by AlexIII** [comment]
> btw, you'll need to change `manifest.json` in the extension so it will work on `chrome-extensions` protocol, which NW.js app uses.

@rogerwang that was it. Thank you!
