### ISSUE TITLE
Dynamic binary eval.

### ISSUE THREAD

**Issue by Kilgaloon** [nwjs/nw.js#5168]
Hello everyone,

I just noticed that when i try to load binary files dynamicaly, for example, using for loop and looping through some array for example:

var arr =  ["home","front"];

for(i=0;i<arr.length;i++) {
    require('nw.gui').Window.get().evalNWBin(null, process.cwd() + '/' + arr[i] + '.bin');
}

home.bin get executed twice. It never get to front.bin.

Anyway no mather how much arr is long, first element will be evaled for arr.length times.

OS: Debian Jessie x64
NW: 0.14.6

**Comment by ghostoy** [comment]
I will look into this issue.

Strahinja <notifications@github.com>于2016年7月30日周六 23:15写道：

**Comment by ghostoy** [comment]
@Kilgaloon I cannot reproduce this issue. Here is my test case: https://gist.github.com/ghostoy/183649c64060b088a610ebc142fae3d2 

I got `foo` and `bar` both in the console.

**Comment by Kilgaloon** [comment]
Can you put for loop in another bin, then try.

**Comment by ghostoy** [comment]
@Kilgaloon What do you mean by "another bin"? A third one?

**Comment by Kilgaloon** [comment]
@ghostoy  Yes, put for loop in third bin, lets say main.bin and try it like that

**Comment by Kilgaloon** [comment]
For me it actually doesn't mather where im doing for loop. im using following snippet of code:

`results = ["main","front","admin"];
        for(i=0;i<=results.length;i++) {
          nw.Window.get().evalNWBin(null, process.cwd() + "/plugins/" + results[i] + "/" + results[i] + ".bin");
        }`

every of this bins have corresponding log depending of their name `console.log('main loaded.')` etc.
So, what ever i do i get `3 main loaded`, if i put front to be first element i will get `3 front loaded`. This is getting weird since you guys can't reproduce this. But im getting same with jQuery.each function or with classic for loop.

**Comment by ghostoy** [comment]
@Kilgaloon Could you upload your entire test app as attachment?

**Comment by Kilgaloon** [comment]
I'll contact you on gitter

**Comment by ghostoy** [comment]
@Kilgaloon It's quite late for me. Please send attachment to Github and I'll check it tomorrow.

**Comment by Kilgaloon** [comment]
Project is kinda big, can you give me some where i can privately share it with you?

**Comment by semmel** [comment]
I can confirm that multiple `evalNWBin` commands always execute just the `.bin` which was first specified. It has nothing to do whether the `bin`s have a relative or absolute path.
System: OS X, nwjs 0.16.0 (SDK)
To demo I took @ghostoy 's gist and added some buttons which trigger the evaluation of the separate bins. See [my fork](https://gist.github.com/semmel/93bf7b838dac4150a66fb71decab3b59). It's funny to watch on the system console.

Is there some caching going on with evalNWBin?

By the way, I noticed that executing `evalNWBin` from the developer console does not work.

**Comment by Kilgaloon** [comment]
I can confirm that also when i start app and momentally open developer console, brhavior will be same like its not included.

**Comment by ghostoy** [comment]
You can send mail to me cong.liux#gmail.com

Strahinja <notifications@github.com>于2016年8月4日周四 18:38写道：

**Comment by ghostoy** [comment]
@rogerwang I can reproduce this issue with 0.14.6 and 0.16.0.

I've updated my gist @ https://gist.github.com/ghostoy/183649c64060b088a610ebc142fae3d2.

Steps to reproduce:

* build foo.js and bar.js with nwjc
* launch the app. `test()` run for first time at start.
* click "test" button. `test()` will run again.
* watch the output in console

This issue seems to be more easier to reproduce on 0.16.0. 

On 0.14.6, it only produces the logs from later script, i.e. `bar.bin`, when run `test()` for a **second time**.

```text
[27680:27680:0805/122054:INFO:CONSOLE(15)] "evalNWBin(null, '/home/user/Workspace/test/nwjc-test/foo.bin')", source: chrome-extension://oaohmlchfoanhbkbdhppgoadbhammijj/index.html (15)
[27680:27680:0805/122054:INFO:CONSOLE(0)] "foo", source:  (0)
[27680:27680:0805/122054:INFO:CONSOLE(15)] "evalNWBin(null, '/home/user/Workspace/test/nwjc-test/bar.bin')", source: chrome-extension://oaohmlchfoanhbkbdhppgoadbhammijj/index.html (15)
[27680:27680:0805/122054:INFO:CONSOLE(0)] "bar", source:  (0)
[27680:27680:0805/122056:INFO:CONSOLE(15)] "evalNWBin(null, '/home/user/Workspace/test/nwjc-test/foo.bin')", source: chrome-extension://oaohmlchfoanhbkbdhppgoadbhammijj/index.html (15)
[27680:27680:0805/122056:INFO:CONSOLE(0)] "bar", source:  (0)
[27680:27680:0805/122056:INFO:CONSOLE(15)] "evalNWBin(null, '/home/user/Workspace/test/nwjc-test/bar.bin')", source: chrome-extension://oaohmlchfoanhbkbdhppgoadbhammijj/index.html (15)
[27680:27680:0805/122056:INFO:CONSOLE(0)] "bar", source:  (0)
```

And on 0.16.0, it always produces the logs from former script, i.e. `foo.bin`:

```text
[27817:27817:0805/122147:INFO:CONSOLE(15)] "evalNWBin(null, '/home/user/Workspace/test/nwjc-test/foo.bin')", source: chrome-extension://oaohmlchfoanhbkbdhppgoadbhammijj/index.html (15)
[27817:27817:0805/122147:INFO:CONSOLE(0)] "foo", source:  (0)
[27817:27817:0805/122147:INFO:CONSOLE(15)] "evalNWBin(null, '/home/user/Workspace/test/nwjc-test/bar.bin')", source: chrome-extension://oaohmlchfoanhbkbdhppgoadbhammijj/index.html (15)
[27817:27817:0805/122147:INFO:CONSOLE(0)] "foo", source:  (0)
[27817:27817:0805/122151:INFO:CONSOLE(15)] "evalNWBin(null, '/home/user/Workspace/test/nwjc-test/foo.bin')", source: chrome-extension://oaohmlchfoanhbkbdhppgoadbhammijj/index.html (15)
[27817:27817:0805/122151:INFO:CONSOLE(0)] "foo", source:  (0)
[27817:27817:0805/122151:INFO:CONSOLE(15)] "evalNWBin(null, '/home/user/Workspace/test/nwjc-test/bar.bin')", source: chrome-extension://oaohmlchfoanhbkbdhppgoadbhammijj/index.html (15)
[27817:27817:0805/122151:INFO:CONSOLE(0)] "foo", source:  (0)
```

**Comment by Kilgaloon** [comment]
Good you reproduced this, one more thing to mention, there is also no difference if you put them in loop or you put them like this (using @ghostoy gist):

    nw.Window.get().evalNWBin(null, process.cwd() + '/foo.bin');
    nw.Window.get().evalNWBin(null, process.cwd() + '/bar.bin');

When i do this to more bins, same thing happen, first always get evaled n times where n = evalNWBin functions.

**Comment by Kilgaloon** [comment]
@ghostoy @rogerwang Is fix for this going to happen anytime soon? im just curious.

**Comment by mscreenie** [comment]
@ghostoy Can bins be loaded via http or https urls?

**Comment by ghostoy** [comment]
@mscreenie No. Currently only supports local files.

**Comment by mscreenie** [comment]
Thanks should I open something to request that as a feature?

**Comment by ghostoy** [comment]
@mscreenie Yes, thanks.

**Comment by rogerwang** [comment]
@Kilgaloon will fix it soon around 0.17 release, which will happen soon.

**Comment by Kilgaloon** [comment]
@rogerwang  Nice to hear that. Can't wait.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

The root cause is NW is using previous cache of code.

**Comment by Kilgaloon** [comment]
Great, nice to hear that, my project has been stalling because of this issue. Can't wait to see this working. Thanks

**Comment by prominentdetail** [comment]
I have this issue on 0.14.7 LTS

**Comment by namaljayathunga** [comment]
I still have this issue on 0.14.7 LTS. Please fix this issue. thanks

**Comment by xianlong1226** [comment]
Due to our system to support the xp, we have to use 0.14.7 version, please repair this version as much as possible.
