### ISSUE TITLE
nwjs 0.14.6 use PepperFlash wiLL show a console window and the text is "NOT SANDBOXED"

### ISSUE THREAD

**Issue by teamers** [nwjs/nw.js#5278]
nwjs version :0.14.6
os:windows 7
In my project,I want support view pages include flash,so i put the plugin files (including ‘manifest.json’ of it) in the ‘PepperFlash’ subdirectory under NW.js binary. 
after that, nwjs had loaded PepperFlash.this can be find in
![image](https://cloud.githubusercontent.com/assets/11494333/18306480/9ef517ce-751e-11e6-9910-27a742f6377f.png)
but when Visit any flash website
For a split second, a console window is opened with the text NOT SANDBOXED.
![image](https://cloud.githubusercontent.com/assets/11494333/18306566/017de826-751f-11e6-9a72-cbbf005f4348.png)

I had try to use PepperFlash  from 14.0.0.177  to 22.0.0.209,the issue always exists.
thank for your reading and  looking forward to your reply

**Comment by rogerwang** [comment]
@Christywl could you please verify this first?

**Comment by Christywl** [comment]
@rogerwang , my test results:
Linux: ` nwjs-sdk-0.20.3` and `PepperFlash 24.0.0.221`, flash works fine. But there is 'NOT SANDBOXED' in the console .
Windows: `nwjs-sdk-0.20.3` and `PepperFlash 24.0.0.221`, flash doesn't work and it shows 'Couldn't load plugin'
Windows: `nwjs-sdk-0.20.3` and `PepperFlash 19.0.0.245`, this issue reproduced, a console window flickered.

my package.json for Windows
```
{
  "name": "Test",
  "main": "http://www.adobe.com/software/flash/about",
  "chromium-args": "--ppapi-flash-path=C:\\nwjs\\PepperFlash\\24.0.0.221\\pepflashplayer.dll"
}
```
my package.json for Linux:
```
{
  "name": "Test",
  "main": "http://www.adobe.com/software/flash/about/",
  "chromium-args": "--ppapi-flash-path=/home/***/.config/google-chrome/PepperFlash/24.0.0.221/libpepflashplayer.so"
}
```

**Comment by rogerwang** [comment]
@Christywl for the 2nd scenario under which flash doesn't work, could you please try with http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Flash%20Plugin/

**Comment by Christywl** [comment]
@rogerwang , I referred to the docs, put PepperFlash folder(including manifest.json/pepflashplayer.dll) under the `nwjs-sdk-v0.20.3-win-x64`, but 'Couldn't load plugin' still occurred. I checked with `nw -url="chrome://plugins"`, and enabled the flash plugin. But it doesn't take effect.
cmd: 
`nw.exe --url=http://www.adobe.com/software/flash/about`
or 
`nw.exe --url=http://www.adobe.com/software/flash/about --ppapi-flash-path=PepperFlash\pepflashplayer.dll`

```
Environment:
Windows
nwjs-sdk-0.20.3
PepperFlash 24.0.0.221(built-in of Chrome)
```


![1](https://cloud.githubusercontent.com/assets/20039821/23737949/09f80d46-04d1-11e7-9216-380f4ce61752.png)


![2](https://cloud.githubusercontent.com/assets/20039821/23737951/0c5803fc-04d1-11e7-89db-66ebde0efe81.png)

**Comment by RohitSharma27** [comment]
I can confirm that this issue is still there in 0.14.7 LTS. @Christywl You can place the `pepflashplayer.dll` along with nw.exe and launch the application with these arguments ` --ppapi-flash-path=pepflashplayer.dll --ppapi-flash-version=<version>`. In my case, a cmd window open up and closes in a split second which says "not sandboxed". I hope you should be able to load the plugin on windows now.

**Comment by Christywl** [comment]
@RohitSharma27 , yes, as I mentioned in my first comment(the 3rd scenario), I could reproduce your issue with nwjs-sdk-0.20.3 and *PepperFlash 19.0.0.245*. But if I used the latest `PepperFlash 24.0.0.221`, I saw 'Couldn't load plugins'. I thought your PepperFlash version may be lower than 24.0.0.221.

**Comment by rogerwang** [comment]
@Christywl I just tried: latest 0.21 works with latest flash plugin 25 under windows.

**Comment by rogerwang** [comment]
The console window flicker is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
reopen since the patch need further review.

**Comment by rogerwang** [comment]
fixed again in git and will be available in the next nightly build.

**Comment by icemoegirl** [comment]
The console window still flicker when using webview to load flash website.
nw.js version: 0.22.0
os version: windows 10
flashplayer version: 25.0.0.148

**Comment by sourceskyboxer** [comment]
@Christywl, Warning!!!
Last picture Couldn't load plugin = It is seen wrong architecture of plugin! And make sure current 64 and 32 Bit version.

PS: It is not bug. And externalinterface always throw SecurityError :/

**Comment by josh83abc** [comment]
Hi guys!

I'm using NW.JS v30.5 and PepperFlash v29, all 32 bits, and **I still have a flashing console (cmd.exe) window when using Flash content in my app!** I got complains from users thinking it is a malware, so I would like to remove this windows.

The flashing console windows appears at the right moment I'm loading Flash content on the HTML page. Basically I do it at startup, but it can also be at another time

The flashing console windows lasts 100ms and don't display any message, or maybe it closes too fast to display anything. 

I tried with several flash contents (SWF), some even without actionscript, the flashing window still appear.  I also removed the "echo 'NOT SANDBOXED'" in pepflashplayer.dll, no effect too.

Please help, thanks in advanced
Josh
