### ISSUE TITLE
crash on localStorage.getItem('url') 0.23.0

### ISSUE THREAD

**Issue by bjoernneumann** [nwjs/nw.js#5947]
nwjs 0.23.0 exits when executing localStorage.getItem('url').

To reproduce get 0.23.0 sdk, run, open devtools and execute localStorage.getItem('url') in the console.
nwjs closes immediately.
Other parameters than 'url' work, like localStorage.getItem('abc')

Happens on Linux and Windows. Works on MacOSX.

**Comment by bjoernneumann** [comment]
It's getting a bit weird now with the string 'url':

open devtools again and execute:

var el = document.createElement('input');
el.setAttribute('type', 'url'); // > crash
OR
el.type = 'url'; // > crash

So 'url' seems to have some strange side effects...

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
This is because the string constant 'url' is initialized in Node with different 'ExternalOneByteStringResource' subclass with Blink. So when Blink tries to convert it to its own subclass NW crashes with invalid pointer...

**Comment by rogerwang** [comment]
please try this build: https://dl.nwjs.io/live-build/06-08-2017/nw23-f975f3e-ca7d50f-ef801be-38a0da7/v0.23.1/

**Comment by bjoernneumann** [comment]
Tried the builds from https://dl.nwjs.io/live-build/06-08-2017/nw23-f975f3e-ca7d50f-ef801be-38a0da7/v0.23.1/.
But unfortunately still the same problem.

**Comment by rogerwang** [comment]
Oops. the change was not correct built. Will build another one soon.

**Comment by bjoernneumann** [comment]
Ok great. Thanks for the fast fix.

**Comment by rogerwang** [comment]
Please try again with https://dl.nwjs.io/live-build/06-08-2017/nw23-2bad83e-ca7d50f-ef801be-1ac5823/v0.23.1/

**Comment by bjoernneumann** [comment]
@rogerwang Works! Thank you very much.
