### ISSUE TITLE
NW.js (0.22.0+) "--in-process-gpu" Causes Severe Problems With Application Instancing

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#6059]
**General Information:**
- Using NW.js version 0.22.0 & newer
- Windows 7 with latest drivers
- [Package.nw](https://github.com/nwjs/nw.js/files/1178513/package.zip) (unzip before use)

**Problem Description:**
I'm running a packaged _Construct 2_ game (HTML5).
I've recently noticed an issue with the "--in-process-gpu" chromium arg, which started occurring using the mentioned versions above. This issue for an unknown reason causes NW.js to not run at all, when launched through 3rd party programs such as [_Steam_](http://store.steampowered.com/about/) or in _[Construct 2's](https://www.scirra.com/) Preview Mode_.

I could figure out reliable ways to reproduce this issue, it seems like it's somehow related to application instancing (running multiple application instances at once, which shouldn't be possible by default).

**Steps to reproduce (instance issue):**
<1> Run the attached package.nw file using NW.js 0.22.0+
<2> Run more instances and notice that they all run in the background (this shouldn't be possible!)
<3> Notice that the other instances have growing memory use and close themselves after about 5-10sec.
(In rare cases some of these additional processes keep running and require to be closed manually.)

**Steps to reproduce (3rd party "ghost process" issue):**
<1> Put the attached package.nw file inside the same folder where your NW.js executable is
<2> Add "nw.exe" as a non-steam game into your Steam Library ([?](https://support.steampowered.com/kb_article.php?ref=2219-YDJV-5557&l=english))
<3> Run "nw.exe" using Steam (this might require multiple attempts or not work at all)
<4> Notice that NW.js doesn't run at all because of processes that keep running in the background

**Observed Result**
Using the "--in-process-gpu" chromium arg in NW.js v0.22.0+, causes severe problems and sometimes even makes it impossible to run NW.js through 3rd party programs at all.

Since I couldn't reproduce these issues using NW.js v0.21.0, I assume that NW.js v0.22.0+ must have introduced some _behind-the-scenes_ changes to application instancing, which don't seem to work in combination with the mentioned chromium arg.

I also wasn't able to reproduce these issues without using "--in-process-gpu", so it's save to assume that this particular chromium arg is at fault.

**Expected Result**
I expect it to work as it did in previous versions, since it is required in order to launch the [Steam Overlay](https://support.steampowered.com/kb_article.php?ref=9394-yofv-0014&l=english).

**Comment by Christywl** [comment]
I can reproduce the issue(instance issue) on Windows with nwjs-sdk-v0.24.0.

**Comment by zydrone** [comment]
Any news on in which release this bug expected to be fixed?

**Comment by TheRealDannyyy** [comment]
@Christywl @rogerwang Any updates about this, will this be fixed in next major NW.js release? 
This is an impactful problem for everything videogame related, since they require this arg in order to run.

**Comment by rogerwang** [comment]
@TheRealDannyyy could you please provide a version than can run in the Chromium browser?

**Comment by TheRealDannyyy** [comment]
@rogerwang [HERE](https://cdn.discordapp.com/attachments/225550155531812865/354213411003039744/In-Process_Testing.zip) is the Chromeapp version of it. 
(I'm not sure how to add chromium args to it so you have to add _--in-process-gpu_ to it.)

**Comment by rogerwang** [comment]
I just fixed the instance issue in git. Let's wait for the next 0.25 build and see how it works for the 2nd issue.

**Comment by TheRealDannyyy** [comment]
Thanks, I hope this will be back-ported to all previous versions as well (if possible).
No worries about reproducing the 2nd issue, I will test it on my end and post my results.

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/09-19-2017/nw25-62eda86-f69a3eb-f685c1b-2cfe2ea/v0.25.3/

**Comment by TheRealDannyyy** [comment]
The issue within NW.js itself seems to be fixed (when starting it directly), however there is still a problem when NW.js is being launched through another program. It either takes up to 5min to start up or doesn't start at all and leaves ghost processes behind.

Not sure how I could help with debugging and finding out what goes wrong.

**Comment by zydrone** [comment]
@TheRealDannyyy sorry to hear that. Was just about to get excited when I saw the potential fix posted. Still, thanks @rogerwang for taking a stab at this. I hope it is still possible to fix somehow.

**Comment by rogerwang** [comment]
The 2nd issue works now.

**Comment by icesunx** [comment]
Has this bug  been fixed？I just try the build from https://dl.nwjs.io/live-build/10-16-2017/nw26-744df00-edf758a-6de1a29-61e38b8/v0.26.0/  
and it seem reproduce the “3rd party "ghost process" issue”. nw.js always worked fine on my computer(win7-64 and win10-64). But some people( they use win7-64 or win7-32) launch my app from Steam with the arg "--in-process-gpu" will get "ghost process"...

**Comment by TheRealDannyyy** [comment]
@rogerwang This is defiantly not fixed, neither issue _1_ nor issue _2_.
You can still reproduce issue #1 by simply spam-clicking on nw.exe using NW.js v0.26.0 on Windows 7 (64 bit

I would like to request to open this issue again!

**Comment by rogerwang** [comment]
did you see it in 0.25.4?

**Comment by TheRealDannyyy** [comment]
I cannot reproduce issue _1_ using version NW.js v0.25.4 but I can reproduce issue _2_.

**Comment by rogerwang** [comment]
@Christywl please verify. Last time I tried, 0.25.4 is working for me in both cases.

@TheRealDannyyy that's the incompatibility that the assumption stream made on the applications and the multi-process architecture of Chromium. And in-process mode is not something that every applications want.

**Comment by Christywl** [comment]
nwjs-sdk-v0.26.0, it works fine.
![image](https://user-images.githubusercontent.com/20039821/31873355-4b5f7bde-b7f5-11e7-930f-f03b2ecd70f6.png)
![image](https://user-images.githubusercontent.com/20039821/31873373-5d4121d6-b7f5-11e7-9f0c-47c522848a45.png)

**Comment by icesunx** [comment]
I can use nwjs(juse unzip the file "nwjs-v0.25.4-win-ia32.zip") without app file to reproduce the "ghost process" issue in my friend's computer, so I think the problem is not related to app files.
I find that about 1/10 people who bought my game reproduce the issue(with nw 0.22.4, win7) . The leader of us didn't allow me to update nw before it solve the problem, so we just remove the arg "--in-process-gpu". Now they can play my game but without steam overlay.
Maybe you need to find a environment which reproduce the "ghost process" issue, because it can't be reproduce in every computer .
To test the issue in Steam, you can add a "non-steam game".
If you need a steam key of my game to test the issue, please give me your contact information(maybe e-mail), I'll give you one.

**Comment by rogerwang** [comment]
I can reproduce the steam issue now with one of our systems. Will look for a fix soon.

**Comment by rogerwang** [comment]
The root cause is actually not in NW. While I'm still searching for a workaround, could you please try this build in your system? https://dl.nwjs.io/live-build/10-21-2017/nw27-50e9d4d-af7e38e-266ada3-0be98a3/v0.27.0-canary/

**Comment by TheRealDannyyy** [comment]
> The root cause is actually not in NW. While I'm still searching for a workaround, could you please try this build in your system? https://dl.nwjs.io/live-build/10-21-2017/nw27-50e9d4d-af7e38e-266ada3-0be98a3/v0.27.0-canary/

@rogerwang Can confirm that both issues are fixed using that version.
Tested on Windows 7 (64bit), latest version of Steam.

**Comment by rogerwang** [comment]
Good to know it. Now the plan is to resolve this in in the 0.27 beta, which will be released soon. Working around it in 0.26 would be much harder due to it's a race condition in software from 3rd party vendor.

**Comment by TheRealDannyyy** [comment]
It's alright for me if this is not getting backported, as long as it works in future versions of NWjs. 
Thanks for the fix and everyone that participated in solving this issue!

**Comment by rogerwang** [comment]
Release candidate: https://dl.nwjs.io/live-build/11-29-2017/nw27-4a542eb-d157415-665d7cd-c0569cf/v0.27.0/

It will be updated again after upstream refreshes.
