### ISSUE TITLE
http2.connect always fails with Uncaught NodeError: Invalid URL on Windows

### ISSUE THREAD

**Issue by cTn-dev** [nwjs/nw.js#6444]
NWJS Version : v0.28.0 (Latest at the time of writing)
Operating System : Windows 10 x64

### Expected behavior
ClientHttp2Session should have been returned
### Actual behavior
Uncaught NodeError: Invalid URL: https://localhost:1234
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at Object.connect (internal/http2/core.js:2552:17)
### How to reproduce
You can simply test this by opening an inspector and pasting the following code into the console
```
const http2 = require('http2');
const clientSession = http2.connect('https://localhost:1234');
```

**Comment by rogerwang** [comment]
This is fixed in git and is available at: https://dl.nwjs.io/live-build/nw28/02-05-2018/c91f2ce-5bae971-f62d7a0-44a6e80/v0.28.1/

**Comment by cTn-dev** [comment]
@rogerwang the c91f2ce497b871dd0d472b355f16119d823fe0ce fixed it in the webkit context (regular NW.js/inspector console) but it still breaks within node context with 

```
const http2 = require('http2');
http2.connect('https://api.example.com')

TypeError [ERR_INVALID_URL]: Invalid URL: https://api.example.com
```

As a node context i mean using http2.connect inside a node forked child process.
I can write you some demo/example code if needed.

**Comment by rogerwang** [comment]
I see. Will fix that case after 0.28.1 release.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/nw28/02-06-2018/44fe510-5bae971-d4482d6-9cda2d7/v0.28.2/

**Comment by cTn-dev** [comment]
@rogerwang thanks, this indeed fixes it in node context, yay 8-)
Howeve, it would seem that establishing a valid connection in webkit context now completely crashes NW.js
Try with this url in inspector/console for example, everything closes after 2 or so seconds (this was happening with the 0.28.1 as well it seems (i haven't tested it very extensively before, since my goal is to use it in node context, sorry)

```
var http2 = require('http2');
http2.connect('https://api.binance.com');
```

**Comment by rogerwang** [comment]
It works for me. Could you please give a complete sample?

**Comment by rogerwang** [comment]
oops. wrong OS.

**Comment by cTn-dev** [comment]
:-) so does it indeed crashes on your Win 10 x64 machine?

**Comment by rogerwang** [comment]
Yeah. it works for me on win10 x64. Could you provide a full sample?

**Comment by cTn-dev** [comment]
I have an rather big project where i am using this, ill try to shrink it down as much as i can and get back to you (it might take a while).

**Comment by cTn-dev** [comment]
@rogerwang 
The example runs (it appears to keep running when you don't touch it) but when you right click on the content and open inspector it force closes, leaving this in the debug.log

`[0206/063908.540:ERROR:http_transport_win.cc(175)] WinHttpCrackUrl: The URL does not use a recognized protocol (0x2ee6)`

This is on Windows 10 Home x64 version 1709 (OS Build 16299.192)

[example.zip](https://github.com/nwjs/nw.js/files/1697863/example.zip)

**Comment by cTn-dev** [comment]
@rogerwang is there anything i can do/test to help you debug this Roger?
I find it really odd that it works fine inside a node context (in a forked child process), but it crashes so badly inside webkit/nw.js.

**Comment by rogerwang** [comment]
I can reproduce it with your sample. I just pushed a fix for this. The next nightly build will have it.

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/nw28/02-09-2018/abfe854-5bae971-d4482d6-a341d52/v0.28.2/

**Comment by cTn-dev** [comment]
Thanks @rogerwang i tested it and it appears to be fixed.

**Comment by dominic-simplan** [comment]
If I use nwjc to protect the source code and nw-builder to package the app, I am still getting this error for the example provided by @cTn-dev with nw.js v0.29.1.
Is this an issue with nw-builder then or where would be the right place to ask?

**Comment by weiluenju** [comment]
Same issue with @dominic-simplan , help~

**Comment by weiluenju** [comment]
I solved the issue by myself.
The problem is I protect my code by nwjs on x64 OS, but pack and build it into x86 platform.
Just change the build target to x64 and every thing is OK.
