### ISSUE TITLE
NW2: Clicks on the tray icon not being sent to function.

### ISSUE THREAD

**Issue by raguay** [nwjs/nw.js#7297]
NWJS Version : 0.43.3
Operating System : macos 10.14.6

### Expected behavior

I have a function that should be called on tray clicking to show/hide the main window. Each click show either show the window if it's not being shown, or hide the window if it is shown. It did this fine in the pre-NW2 builds (I believe 0.39 was the last version I was on before switching to the 0.43 builds).

### Actual behavior

Right after launch, it works great. But, after an indeterminable amount of time (I haven't found a amount of time or action that causes it to stop processing the clicks), clicking does nothing. 

Since the program has a build in server, I added a route to show the window with a get request to a specific route. When it quits working, I send a get request on that route. The window shows and then quickly hides/shows until all the click events that did not go through are done being processed.

### How to reproduce

I guess make a tray application that shows and hides the window based on clicking on the tray icon. It should show the same behavior. I haven't made a smaller app with just that feature. I'm using my full application that is fairly large.

**Comment by rogerwang** [comment]
Could you please provide a full sample (not code snippets) so we can reproduce?

**Comment by connectiblutz** [comment]
We are experiencing this issue as well with the NW2 builds. Attached is a small example project. 

Steps to reproduce:
- Load in 0.43.3 Windows x64
- Close the window via the X to minimize it to the system tray
- Wait some amount of time (15-30 minutes usually does the trick)
- Click the tray icon, or right click and choose Show.

If you try to show the window shortly after minimizing to tray, it seems to always reshow properly. But waiting awhile before reshowing it, the javascript seems to no longer run. Both Show and Exit options from the tray menu no longer function.

Having a developer tools window open while hidden seems to keep everything functional. Disabling NW2 via chromium-args also seems to work around this. Versions prior to NW2 (0.42.3 and earlier) don't exhibit this.

[TrayTest.zip](https://github.com/nwjs/nw.js/files/4026981/TrayTest.zip)

**Comment by raguay** [comment]
I have a minimal version of my application that displays the same behavour. Unzip the file and go to the public directory and run nwjs in it. If you don’t click on the icon in the taskbar for a while, it stops responding. If you click on it right away and every few minutes (not more than 3 minutes), it keep working fine. This is a Svelte application, but very minimal.
[Test.zip](https://github.com/nwjs/nw.js/files/4029973/Test.zip)

**Comment by raguay** [comment]
BTW: I’m running everything on a macOS 10.14.6 with nwjs version 43.3 nightly (1-4-2020).

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200112-162000/425569548

**Comment by raguay** [comment]
Thanks so much. My app has been running several hours now and I can still click on the tray icon to have it appear. Now, onward to my other bugs. Thanks again.

**Comment by betsonserviceportal** [comment]
As far as I can tell this is still an issue in v44.  This was happening back in v34, it seemed to get better and now it's worse than ever.
