### ISSUE TITLE
NW.js throws error when zip file not present on every execution

### ISSUE THREAD

**Issue by Sunvas** [nwjs/nw.js#7882]
NWJS Version : 0.64
Operating System : Windows 10

After closing program file debug.log is created alongside nw.exe with strange contents:

```
[0514/214309.922:ERROR:zip_reader.cc(132)] Cannot open ZIP from file handle 00000000000001A8
[0514/214309.922:ERROR:zip.cc(202)] Cannot open ZIP from file handle 00000000000001A
```

**Comment by djmisterjon** [comment]
ya , i also dont know what this is , its probably a old plugin or dependency not removed correcly in nwjs.
you can also see it in verbose mode
![image](https://user-images.githubusercontent.com/24865815/168502826-66c32e94-f87c-40d0-b29a-ba72a6f310d8.png)

**Comment by sysrage** [comment]
@rogerwang I'm also getting this with all of my projects when using either 0.64.0 or 0.64.1 in either Windows 10 or Linux (Ubuntu 20.04). Can you please look into it?

**Comment by djmisterjon** [comment]
it is can be related to this line?
Is the only trace of `zip` i can found
https://github.com/nwjs/nw.js/blob/8992bb621ce3878fb72ea35e6c7b94a32e289ee5/src/nw_package.cc#L40
am not experimented in C

**Comment by sysrage** [comment]
This is still an issue with 0.65.1. I can confirm it happens in every OS.

**Comment by Sunvas** [comment]
live-build/nw66 - same issue

```
[0622/181233.966:ERROR:zip_reader.cc(153)] Cannot open ZIP from file handle 000000000000008C
[0622/181233.967:ERROR:zip.cc(202)] Cannot open ZIP from file handle 000000000000008C
```

**Comment by TheJaredWilcurt** [comment]
@rogerwang This issue is still present

**Comment by lachezarR** [comment]
This does not happen on 0.66.0 on my system but it happens with 0.66.1. Was this fixed in 0.66.0 and it was broken on the newest, or should I be looking for some config that worked with 0.66.0 but not with 0.66.1?

**Comment by sysrage** [comment]
This **does** happen with 0.66.0. It is not a configuration issue, it is a bug that @rogerwang will need to fix.

**Comment by lachezarR** [comment]
> This **does** happen with 0.66.0. It is not a configuration issue, it is a bug that @rogerwang will need to fix.

I mean 0.60.0. It's strange that the so called package.nw is not in /opt/nwjs folder for 0.60.0 as well, but it does not throw this error and build succeeds.

**Comment by Sunvas** [comment]
Same issue on 0.67, but `debug.log` is empty.

**Comment by rogerwang** [comment]
Fix released with 0.67.1

**Comment by JohnLego** [comment]
Finally! It's fixed! Now this topic should be closed since the resolution came even though it should have 4 months ago.

**Comment by djmisterjon** [comment]
> Finally! It's been fixed! Now this topic should be closed since the resolution came even though it should have 4 months ago.

relax friend!, it work alone and nw is free

**Comment by corwin-of-amber** [comment]
Hello @rogerwang, thanks for the fix! Now I am not seeing the error about package.nw not existing, but I still get an error for app.nw:
```
Cannot open '/opt/homebrew/lib/node_modules/nw/nwjs/nwjs.app/Contents/Resources/app.nw': FILE_ERROR_NOT_FOUND: No such file or directory (2)
```
(installed via `npm i -g` over a Homebrew installation on macOS Monterey)
